language: node_js
matrix:
  include:
    - os: linux
      node_js: "8"
    - os: linux
      node_js: "10"
    - os: linux
      node_js: "12"
    - os: linux
      node_js: "14"
    - os: osx
      node_js: "8"
    - os: osx
      node_js: "10"
    - os: osx
      node_js: "12"
    - os: osx
      node_js: "14"
