os: Visual Studio 2014 CTP4
version: "{build}"
build: off
platform:
  - x86
  - x64
environment:
  matrix:
  - nodejs_version: "0.10"
  - nodejs_version: "0.12"
  - nodejs_version: "2"
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install --msvs_version=2013
test_script:
  - npm test
