os: Visual Studio 2019
version: "{build}"
build: off
platform: x86
environment:
  matrix:
  - nodejs_version: "10"
  - nodejs_version: "12"
  - nodejs_version: "14"
  - nodejs_version: "15"
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
test_script:
  - npm test
